--------------------------------------------------------
--  DDL for Index T_20_HM_EMP_MRT_STA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM"."T_20_HM_EMP_MRT_STA_PK" ON "HCM"."T_20_HM_EMP_MRT_STA" ("R_K") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
