--------------------------------------------------------
--  DDL for Index T_99_SSU_PWD_PRF_CON
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM"."T_99_SSU_PWD_PRF_CON" ON "HCM"."T_99_SSU_PWD_PRF" ("PRF_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
