--------------------------------------------------------
--  Constraints for Table T_99_SSU_USR
--------------------------------------------------------

  ALTER TABLE "HCM"."T_99_SSU_USR" MODIFY ("R_K" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_USR" MODIFY ("USR_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_USR" MODIFY ("UPD_DT" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_USR" MODIFY ("IUS_YN" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_USR" ADD CONSTRAINT "T_99_SSU_USR_PK" PRIMARY KEY ("R_K")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM"."T_99_SSU_USR" ADD CONSTRAINT "T_99_SSU_USR_UK1" UNIQUE ("USR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
