--------------------------------------------------------
--  Constraints for Table T_99_SSU_ACC
--------------------------------------------------------

  ALTER TABLE "T_99_SSU_ACC" MODIFY ("R_K" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_ACC" MODIFY ("ACC_CD" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_ACC" MODIFY ("SHT_NM" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_UK1" UNIQUE ("SHT_NM")
  USING INDEX  ENABLE;
  ALTER TABLE "T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_PK" PRIMARY KEY ("R_K", "ACC_CD")
  USING INDEX  ENABLE;
  ALTER TABLE "T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_UK" UNIQUE ("ACC_CD")
  USING INDEX  ENABLE;
