--------------------------------------------------------
--  Constraints for Table T_99_SSU_ACC
--------------------------------------------------------

  ALTER TABLE "HCM"."T_99_SSU_ACC" MODIFY ("R_K" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_ACC" MODIFY ("ACC_CD" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_ACC" MODIFY ("SHT_NM" NOT NULL ENABLE);
  ALTER TABLE "HCM"."T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_UK1" UNIQUE ("SHT_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM"."T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_PK" PRIMARY KEY ("R_K", "ACC_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM"."T_99_SSU_ACC" ADD CONSTRAINT "T_99_SSU_ACC_UK" UNIQUE ("ACC_CD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
