--------------------------------------------------------
--  DDL for Table HM_EMAIL_TEMPLATES
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_EMAIL_TEMPLATES" 
   (	"ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(255 BYTE), 
	"FULL_TEMPLATE_HTML" CLOB, 
	"TEXT_TEMPLATE" VARCHAR2(4000 BYTE), 
	"TABLE_OPEN_HTML" VARCHAR2(4000 BYTE), 
	"TR_HTML" VARCHAR2(4000 BYTE), 
	"TABLE_CLOSE_HTML" VARCHAR2(4000 BYTE), 
	"ACTION_BUTTON_HTML" VARCHAR2(4000 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FULL_TEMPLATE_HTML") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
