--------------------------------------------------------
--  DDL for Table HM_EMAIL_AFFECTS
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_EMAIL_AFFECTS" 
   (	"ID" NUMBER, 
	"EMAIL_ID" NUMBER, 
	"USERNAME" VARCHAR2(255 BYTE), 
	"USER_TZ_PREF" VARCHAR2(60 BYTE), 
	"USER_LANG_CODE" VARCHAR2(10 BYTE), 
	"USER_OPTED_OUT_YN" VARCHAR2(1 BYTE), 
	"EMAIL_SENT_ON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"EMAIL_ERROR" VARCHAR2(4000 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
