--------------------------------------------------------
--  DDL for Table HM_EMAILS
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_EMAILS" 
   (	"ID" NUMBER, 
	"TEMPLATE_ID" NUMBER, 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"BODY1_TEXT" VARCHAR2(4000 BYTE), 
	"TABLE_CONTENT" VARCHAR2(4000 BYTE), 
	"BODY2_TEXT" VARCHAR2(4000 BYTE), 
	"ACTION_LABEL" VARCHAR2(70 BYTE), 
	"ACTION_LINK" VARCHAR2(4000 BYTE), 
	"CAN_OPT_OUT_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"EMAIL_BODY" CLOB, 
	"NBR_EMAILS_SENT" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("EMAIL_BODY") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
