--------------------------------------------------------
--  DDL for Table HM_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_FEEDBACK" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"USER_AGENT" VARCHAR2(4000 BYTE), 
	"FEEDBACK" VARCHAR2(4000 BYTE), 
	"RESPONSE" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
