--------------------------------------------------------
--  DDL for Table HM_NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_NOTIFICATIONS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"NOTIFICATION_NAME" VARCHAR2(255 BYTE), 
	"NOTIFICATION_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"NOTIFICATION_TYPE" VARCHAR2(30 BYTE), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"DISPLAY_FROM" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"DISPLAY_UNTIL" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
