--------------------------------------------------------
--  DDL for Table HM_PREFERENCES
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_PREFERENCES" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"PREFERENCE_NAME" VARCHAR2(100 BYTE), 
	"PREFERENCE_VALUE" VARCHAR2(4000 BYTE), 
	"IS_REQUIRED_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DATATYPE" VARCHAR2(5 BYTE) DEFAULT 'TEXT', 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"VALID_VALUES" VARCHAR2(4000 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
