--------------------------------------------------------
--  DDL for Table HM_USERS
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_USERS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"EMAIL_ADDRESS" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"WORK_PHONE" VARCHAR2(30 BYTE), 
	"MOBILE_PHONE" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(4000 BYTE), 
	"PHOTO_BLOB" BLOB, 
	"PHOTO_NAME" VARCHAR2(512 BYTE), 
	"PHOTO_MIMETYPE" VARCHAR2(512 BYTE), 
	"PHOTO_CHARSET" VARCHAR2(512 BYTE), 
	"PHOTO_LASTUPD" DATE, 
	"NOTE" VARCHAR2(4000 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO_BLOB") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
