--------------------------------------------------------
--  DDL for Table HM_USER_PREFERENCES
--------------------------------------------------------

  CREATE TABLE "HCM"."HM_USER_PREFERENCES" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"USER_ID" NUMBER, 
	"PREFERENCE_NAME" VARCHAR2(100 BYTE), 
	"PREFERENCE_VALUE" VARCHAR2(4000 BYTE), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
