--------------------------------------------------------
--  DDL for Table T_20_HM_EMP_CERT
--------------------------------------------------------

  CREATE TABLE "HCM"."T_20_HM_EMP_CERT" 
   (	"R_K" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CERT_CODE" VARCHAR2(128 BYTE), 
	"CERT_NAME" VARCHAR2(128 BYTE), 
	"CERT_GRADE" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
