--------------------------------------------------------
--  DDL for Table T_20_HM_EMP_TRAN
--------------------------------------------------------

  CREATE TABLE "HCM"."T_20_HM_EMP_TRAN" 
   (	"R_K" NUMBER, 
	"TRAN_CD" NUMBER, 
	"TRAN_DESC" VARCHAR2(128 BYTE), 
	"ACC_CD" RAW(20), 
	"APR_STA" NUMBER, 
	"APR_DT" DATE, 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"RUN_CD" VARCHAR2(52 BYTE), 
	"EMP_NO" VARCHAR2(128 BYTE), 
	"PRC_YN" NUMBER, 
	"NEW_TRAN" NUMBER, 
	"OLD_TRAN" NUMBER, 
	"NEW_TRAN2" NUMBER, 
	"OLD_TRAN2" NUMBER, 
	"NEW_TRAN3" NUMBER, 
	"OLD_TRAN3" NUMBER, 
	"NEW_TRAN4" NUMBER, 
	"OLD_TRAN4" NUMBER, 
	"NEW_TRAN5" NUMBER, 
	"OLD_TRAN5" NUMBER, 
	"APR_BY" VARCHAR2(52 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
