--------------------------------------------------------
--  DDL for Table T_20_HM_EMP
--------------------------------------------------------

  CREATE TABLE "HCM"."T_20_HM_EMP" 
   (	"R_K" NUMBER, 
	"EMP_NO" VARCHAR2(128 BYTE), 
	"EMP_TTL" VARCHAR2(52 BYTE), 
	"LST_NM" VARCHAR2(52 BYTE), 
	"FST_NM" VARCHAR2(52 BYTE), 
	"MDL_NM" VARCHAR2(52 BYTE), 
	"BTH_DT" DATE, 
	"BTH_PLC" VARCHAR2(128 BYTE), 
	"EMP_SEX" VARCHAR2(20 BYTE), 
	"EMP_NTY" NUMBER, 
	"NTY_LGA" VARCHAR2(128 BYTE), 
	"MRT_STA" NUMBER, 
	"EMP_PHN" VARCHAR2(128 BYTE), 
	"EMP_EML" VARCHAR2(128 BYTE), 
	"EMP_ADR" VARCHAR2(150 BYTE), 
	"STF_CTG" NUMBER, 
	"EMP_BRCH" NUMBER, 
	"EMP_DEPT" NUMBER, 
	"EMP_UNT" NUMBER, 
	"EMP_DESG" NUMBER, 
	"EMP_DT" DATE, 
	"CFMT_DT" DATE, 
	"EMP_LVL" NUMBER, 
	"EMP_STP" NUMBER, 
	"STF_STA" NUMBER, 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"APR_BY" VARCHAR2(52 BYTE), 
	"APR_DT" TIMESTAMP (6), 
	"ACC_CD" RAW(32), 
	"ADR_CTY" NUMBER, 
	"ADR_STT" VARCHAR2(128 BYTE), 
	"NTY_STT" VARCHAR2(128 BYTE), 
	"ADR_CITY" VARCHAR2(128 BYTE), 
	"NTY_CITY" NUMBER, 
	"ADR_STR" VARCHAR2(150 BYTE), 
	"APR_STA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
