--------------------------------------------------------
--  DDL for Table T_99_SSU_PRIV
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_SSU_PRIV" 
   (	"R_K" NUMBER, 
	"PG_ID" VARCHAR2(52 BYTE), 
	"BT_ID" VARCHAR2(20 BYTE), 
	"PG_DSC" VARCHAR2(512 BYTE), 
	"BT_DSC" VARCHAR2(512 BYTE), 
	"USR_RLE" VARCHAR2(52 BYTE), 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"ROW_VSN" NUMBER, 
	"ACC_CD" RAW(32), 
	"APP_ID" VARCHAR2(52 BYTE), 
	"IUS_YN" VARCHAR2(1 BYTE), 
	"APR_STA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
