--------------------------------------------------------
--  DDL for Table T_99_SSU_USR
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_SSU_USR" 
   (	"R_K" NUMBER(*,0), 
	"COMP_KEY" RAW(32), 
	"USR_ID" VARCHAR2(52 BYTE), 
	"FST_NM" VARCHAR2(52 BYTE), 
	"LST_NM" VARCHAR2(52 BYTE), 
	"USR_EML" VARCHAR2(52 BYTE), 
	"USR_PHN" VARCHAR2(52 BYTE), 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"LST_LOG" TIMESTAMP (6), 
	"IUS_YN" NUMBER, 
	"TRN_APR" NUMBER, 
	"TRN_EDT" NUMBER, 
	"TRN_VEW" NUMBER, 
	"USR_PWD" VARCHAR2(2000 BYTE), 
	"COMP_SUB" VARCHAR2(52 BYTE), 
	"FLEX_01" VARCHAR2(52 BYTE), 
	"FLEX_02" VARCHAR2(52 BYTE), 
	"ROW_VSN" NUMBER, 
	"LGN_CTN" NUMBER, 
	"APR_STA" VARCHAR2(1 BYTE), 
	"PWD_RST" NUMBER, 
	"LST_PWD_RST" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
