--------------------------------------------------------
--  DDL for Table T_99_SSU_ACC
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_SSU_ACC" 
   (	"R_K" NUMBER, 
	"ACC_CD" RAW(32), 
	"ACC_NM" VARCHAR2(128 BYTE), 
	"NUM_USR" NUMBER, 
	"EXP_DT" DATE, 
	"HSH_CD" VARCHAR2(4000 BYTE), 
	"ACC_EML" VARCHAR2(128 BYTE), 
	"ACC_PHO" VARCHAR2(52 BYTE), 
	"NUM_MON" VARCHAR2(20 BYTE), 
	"STA_DT" DATE, 
	"IP_ADR" VARCHAR2(52 BYTE), 
	"ACC_CTY" VARCHAR2(20 BYTE), 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6) DEFAULT NULL, 
	"UPD_DT" TIMESTAMP (6), 
	"ROW_VSN" NUMBER, 
	"IUS_YN" VARCHAR2(1 BYTE), 
	"SHT_NM" VARCHAR2(5 BYTE), 
	"ACC_CITY" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
