--------------------------------------------------------
--  DDL for Table T_99_SSU_LOG
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_SSU_LOG" 
   (	"R_K" NUMBER, 
	"R_T" TIMESTAMP (6), 
	"APP_ID" VARCHAR2(250 BYTE), 
	"PAGE_ID" VARCHAR2(250 BYTE), 
	"SCH_NM" VARCHAR2(250 BYTE), 
	"ERR_CD" VARCHAR2(250 BYTE), 
	"ERR_MSG" VARCHAR2(4000 BYTE), 
	"USR_ID" VARCHAR2(250 BYTE), 
	"PRC_NM" VARCHAR2(250 BYTE), 
	"ERR_STK" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ERR_STK") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
