--------------------------------------------------------
--  DDL for Table T_99_PYR_RUN
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_PYR_RUN" 
   (	"R_K" NUMBER, 
	"RUN_CD" VARCHAR2(52 BYTE), 
	"FST_DAY" DATE, 
	"LST_DAY" DATE, 
	"OPN_DT" DATE, 
	"CLS_DT" DATE, 
	"RUN_STA" NUMBER, 
	"CRT_BY" VARCHAR2(52 BYTE), 
	"CRT_DT" TIMESTAMP (6), 
	"UPD_BY" VARCHAR2(52 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"ACC_CD" RAW(32), 
	"RUN_MON" VARCHAR2(52 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
