--------------------------------------------------------
--  DDL for Table T_99_SSU_USR_RLE
--------------------------------------------------------

  CREATE TABLE "HCM"."T_99_SSU_USR_RLE" 
   (	"R_K" NUMBER, 
	"ROLE_CD" VARCHAR2(30 BYTE), 
	"USR_CD" VARCHAR2(255 BYTE), 
	"ROW_VSN" NUMBER, 
	"CRT_DT" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CRT_BY" VARCHAR2(255 BYTE), 
	"UPD_DT" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPD_BY" VARCHAR2(255 BYTE), 
	"ACC_CD" RAW(32)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
